name: Docker Image CI For who
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub ...
        uses: docker/login-action@v2
        with:
          #registry: index.docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Build the Docker image and push
        id: docker_build_who
        uses: docker/build-push-action@v3
        with:
          #context: /mgx # context 目录似乎不好指定 ./mgx  /mgx 都不对
          file: ./Dockerfile
          platforms: linux/arm64/v8,linux/amd64
          push: true
          tags: hotpot/who:latest,hotpot/who:1.5
